# Generated by Django 5.2.1 on 2025-06-28 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='data_prato',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
